apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\mkarpinskas\Downloads\kompose-windows-amd64.exe --file .\docker-compose.yml convert -c
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: jenkins
  name: jenkins
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
    - name: "50000"
      port: 50000
      targetPort: 50000
  selector:
    io.kompose.service: jenkins
