apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\mkarpinskas\Downloads\kompose-windows-amd64.exe --file .\docker-compose.yml convert -c
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: jenkins-agent1
  name: jenkins_agent1
spec:
  ports:
    - name: "22"
      port: 22
      targetPort: 22
  selector:
    io.kompose.service: jenkins-agent1
