pipeline {
    agent any

    stages {
        stage('Check Style') {
            steps {
                dir('Task04/demo') {
                  sh './gradlew checkstyleMain'
                }
            }
//             post {
//                 always {
//                     junit '**/build/reports/checkstyle/main.html'
//                 }
//             }
        }
        stage('Spot Bugs') {
            steps {
                dir('Task04/demo') {
                  sh './gradlew spotbugsMain'
                }
            }
//             post {
//                 always {
//                     junit '**/build/reports/spotbugs.html'
//                 }
//             }
        }
        stage('Unit Tests') {
            steps {
                dir('Task04/demo') {
                  sh './gradlew test'
                }
            }
            post {
                always {
                    junit '**/build/test-results/test/TEST-*.xml'
                }
            }
        }
        stage('Build') {
            steps {
                dir('Task04/demo') {
                  sh './gradlew build -x test'
                }
            }
        }
    }
}
