pipeline {
    agent any

    stages {
        stage('Check Style') {
            steps {
                dir('Task04/demo') {
                  sh './gradlew checkstyleMain'
                }
            }
        }
        stage('Unit Tests') {
            steps {
                dir('Task04/demo') {
                  sh './gradlew test'
                }
            }
            post {
                always {
                    junit '**/build/test-results/test/TEST-*.xml'
                }
            }
        }
        stage('Build') {
            steps {
                dir('Task04/demo') {
                  sh './gradlew build'
                }
            }
        }
    }
}
