pipeline {
    agent any

    triggers {
        pollSCM('*/5 * * * *')
    }

    stages {
        stage('Compile') {
            steps {
                sh 'echo "Starting compile"'
                sh 'pwd'
                sh 'ls -l'
                dir('Task04/demo') {
                  sh './gradlew clean --no-daemon'
                }
            }
        }
        stage('Unit Tests') {
            steps {
                sh 'echo "Starting Unit Tests"'
            }
            post {
                always {
                    junit '**/build/test-results/test/TEST-*.xml'
                }
            }
        }

    }
}
