name: Build and Publish Image

on:
 push:
   branches: [ "main" ]
 pull_request:
   branches: [ "main" ]

jobs:

 build:

   runs-on: ubuntu-latest

   steps:
   - uses: actions/checkout@v4
   - name: Build the Docker image
     working-directory: ./03 Task
     run: |
       ls -l
       docker build ./files/app/ -t spring-image:latest
   - name: Publish image
     run: echo "Skipping" #docker build -t spring-image:latest -f files/app/Dockerfile .
