name: Task04 Validate Before Merge

on:
  push:
    paths:
      - Task04/**
  pull_request:
    paths:
      - Task04/**

jobs:
#    https://stackoverflow.com/questions/71334373/is-there-a-way-i-can-validate-yaml-files-on-github
  validate-yaml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validate YAML file
        run: yamllint Task04/demo/src/main/resources/application.yml