name: Task03 Build and Publish Image

on:
 push:
   branches: [ "main" ]
   paths:
     - Task03/**
 pull_request:
   branches: [ "main" ]
   paths:
     - Task03/**

jobs:

 build:

   runs-on: ubuntu-latest

   steps:
   - uses: actions/checkout@v4
   - name: Build the Docker image
     run: |
       ls -l
       docker build ./Task03/files/app/ -t mxas1/spring-image:latest
   - name: Publish image
     run: |
       docker login -u mxas1 -p ${{ secrets.DOCKER_HUB_TOKEN }}
       docker push mxas1/spring-image:latest
